stages:
  - dependencies
  - assemble
  - check
  - security
  - deploy

variables:

  CI_LOCAL_IMAGE_DIABETES: $CI_REGISTRY/$CI_PROJECT_PATH/local-daibetes
  CI_LOCAL_IMAGE_MICROBAIOME: $CI_REGISTRY/$CI_PROJECT_PATH/local-microbaiome

  CI_GLOBAL_IMAGE_DIABETES: $CI_REGISTRY/$CI_PROJECT_PATH/global-daibetes
  CI_GLOBAL_IMAGE_MICROBAIOME: $CI_REGISTRY/$CI_PROJECT_PATH/global-microbaiome
  CI_GLOBAL_IMAGE_POSYMED: $CI_REGISTRY/$CI_PROJECT_PATH/global-posymed

  CI_LOCAL_IMAGE_DIABETES_STAGING: $CI_LOCAL_IMAGE_DIABETES:staging
  CI_LOCAL_IMAGE_MICROBAIOME_STAGING: $CI_LOCAL_IMAGE_MICROBAIOME:staging
  CI_GLOBAL_IMAGE_DIABETES_STAGING: $CI_GLOBAL_IMAGE_DIABETES:staging
  CI_GLOBAL_IMAGE_MICROBAIOME_STAGING: $CI_GLOBAL_IMAGE_MICROBAIOME:staging
  CI_GLOBAL_IMAGE_POSYMED_STAGING: $CI_GLOBAL_IMAGE_POSYMED:staging

  CI_LOCAL_IMAGE_DIABETES_PROD: $CI_LOCAL_IMAGE_DIABETES:staging
  CI_LOCAL_IMAGE_MICROBAIOME_PROD: $CI_LOCAL_IMAGE_MICROBAIOME:staging
  CI_GLOBAL_IMAGE_DIABETES_PROD: $CI_GLOBAL_IMAGE_DIABETES:staging
  CI_GLOBAL_IMAGE_MICROBAIOME_PROD: $CI_GLOBAL_IMAGE_MICROBAIOME:staging
  CI_GLOBAL_IMAGE_POSYMED_PROD: $CI_GLOBAL_IMAGE_POSYMED:staging

  CI_LOCAL_IMAGE_DIABETES_LATEST: $CI_LOCAL_IMAGE_DIABETES:latest
  CI_LOCAL_IMAGE_MICROBAIOME_LATEST: $CI_LOCAL_IMAGE_MICROBAIOME:latest
  CI_GLOBAL_IMAGE_DIABETES_LATEST: $CI_GLOBAL_IMAGE_DIABETES:latest
  CI_GLOBAL_IMAGE_MICROBAIOME_LATEST: $CI_GLOBAL_IMAGE_MICROBAIOME:latest
  CI_GLOBAL_IMAGE_POSYMED_LATEST: $CI_GLOBAL_IMAGE_POSYMED:latest



  TAR_FILE_DIR: ".images/"
  TAR_FILE_NAME_LOCAL_DIABETES: "local-image-diabetes.tar"
  TAR_FILE_NAME_LOCAL_MICROBAIOME: "local-image-microbaiome.tar"
  TAR_FILE_NAME_GLOBAL_DIABETES: "global-image-diabetes.tar"
  TAR_FILE_NAME_GLOBAL_MICROBAIOME: "global-imagemicrobaiome-.tar"
  TAR_FILE_NAME_GLOBAL_POSYMED: "global-image-posymed.tar"

  TRIVY_IMAGE: trivy:latest
  TRIVY_TAR: trivy-latest.tar

.docker_login: &docker_login
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.docker_buildx: &docker_buildx
  - docker context create fedDB-context
  - docker buildx create --name fedDBBuilder --use fedDB-context
  - docker buildx inspect --bootstrap

.docker_buildxrm: &docker_buildxrm
  - docker buildx rm fedDBBuilder

.load_trivy_image: &load_trivy_image
  - docker image load -i $TAR_FILE_DIR$TRIVY_TAR

.load_target_image: &load_target_image
  - docker image load -i $TAR_FILE_DIR$TAG-$TAR_FILE_NAME
# format reports to html and junit and fails the pipeline on HIGH,CRITICAL issues
.format_report: &format_report
  - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ -v $PWD:/target $TRIVY_IMAGE convert
    --format template --template "@/contrib/junit.tpl" target/trivy-$REPORT_NAME-full-report.json --severity CRITICAL,HIGH -o target/trivy-$REPORT_NAME-important-report.xml
  - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ -v $PWD:/target $TRIVY_IMAGE convert
    --format template --template "@/contrib/html.tpl" target/trivy-$REPORT_NAME-full-report.json -o target/trivy-$REPORT_NAME-full-report.html
  - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ -v $PWD:/target $TRIVY_IMAGE convert
    --format template --template "@/contrib/html.tpl" target/trivy-$REPORT_NAME-full-report.json --severity HIGH,CRITICAL -o target/trivy-$REPORT_NAME-important-report.html
  - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ -v $PWD:/target $TRIVY_IMAGE convert
    --exit-code 1 --format table target/trivy-$REPORT_NAME-full-report.json --severity HIGH,CRITICAL --dependency-tree

# exports reports as artifacts
.export_reports: &export_reports
  when: always
  expire_in: 1 week
  reports:
    junit: trivy-$REPORT_NAME-important-report.xml
  paths:
    - trivy-$REPORT_NAME-important-report.html
    - trivy-$REPORT_NAME-full-report.html
    - trivy-$REPORT_NAME-full-report.json


install:
  image: node:20-alpine
  stage: dependencies
  script:
    # Install dependencies
    - npm install --prefer-offline
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules

.assemble:
  image: node:20-alpine
  stage: assemble
  needs:
   - install
  script:
    - npm run $SCRIPT
  artifacts:
    paths:
      - dist
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules
    policy: pull

assemble:global-daibetes:
  extends: .assemble
  variables:
    SCRIPT: build-global-dAIbetes

assemble:local-daibetes:
  extends: .assemble
  variables:
    SCRIPT: build-local-dAIbetes

assemble:posymed:
  extends: .assemble
  variables:
    SCRIPT: build-posymed

assemble:global-microbaiome:
  extends: .assemble
  variables:
    SCRIPT: build-global-microbAIome

assemble:local-microbaiome:
  extends: .assemble
  variables:
    SCRIPT: build-local-microbAIome

.check:lint:
  stage: check
  image: node:20-alpine
  needs:
    - install
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules
    policy: pull
  script:
    - npm run $SCRIPT

check:lint:local:
  extends: .check:lint
  variables:
      SCRIPT: lint-local

check:lint:shared:
  extends: .check:lint
  variables:
    SCRIPT: lint-shared-lib

check:lint:global:
  extends: .check:lint
  variables:
    SCRIPT: lint-global

# builds api and db images and saves them as tar files

.check:build:
  image: docker:latest
  stage: check
  services:
    - name: registry.blitzhub.io/docker:dind
      alias: docker
  before_script:
    - mkdir -p $TAR_FILE_DIR
    - *docker_login
  script:
    - docker build -t $CI_IMAGE -f ./Dockerfile .
    - docker save -o $TAR_FILE_DIR$TAG-$TAR_FILE_NAME $TAR_IMAGE
    - echo "API image created at $TAR_FILE_DIR$TAG-$TAR_FILE_NAME"
  artifacts:
    paths:
      - $TAR_FILE_DIR
    expire_in: 1 hour

check:build:local:diabetes-staging:
  extends: .check:build
  dependencies:
    - assemble:local-daibetes
  needs:
    - assemble:local-daibetes
  variables:
    CI_IMAGE: $CI_LOCAL_IMAGE_DIABETES_STAGING
    TAR_FILE_NAME: $TAR_FILE_NAME_LOCAL_DIABETES
    TAR_IMAGE: $CI_LOCAL_IMAGE_DIABETES

check:build:local:microbaiome-staging:
  extends: .check:build
  dependencies:
    - assemble:local-microbaiome
  needs:
    - assemble:local-microbaiome
  variables:
    CI_IMAGE: $CI_LOCAL_IMAGE_MICROBAIOME_STAGING
    TAR_FILE_NAME: $TAR_FILE_NAME_LOCAL_MICROBAIOME
    TAR_IMAGE: $CI_LOCAL_IMAGE_MICROBAIOME

check:build:global:diabetes-staging:
  extends: .check:build
  dependencies:
    - assemble:global-daibetes
  needs:
    - assemble:global-daibetes
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_DIABETES_STAGING
    TAR_FILE_NAME: $TAR_FILE_NAME_GLOBAL_DIABETES
    TAR_IMAGE: $CI_GLOBAL_IMAGE_DIABETES

check:build:global:microbaiome-staging:
  extends: .check:build
  dependencies:
    - assemble:global-microbaiome
  needs:
    - assemble:global-microbaiome
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_MICROBAIOME_STAGING
    TAR_FILE_NAME: $TAR_FILE_NAME_GLOBAL_MICROBAIOME
    TAR_IMAGE: $CI_GLOBAL_IMAGE_MICROBAIOME

check:build:global:posymed-staging:
  extends: .check:build
  dependencies:
    - assemble:posymed
  needs:
    - assemble:posymed
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_POSYMED_STAGING
    TAR_FILE_NAME: $TAR_FILE_NAME_GLOBAL_POSYMED
    TAR_IMAGE: $CI_GLOBAL_IMAGE_POSYMED

# load the latest trivy image and save as artifact for reuse
security:prepare:
  stage: security
  image: docker:latest
  dependencies: []
  services:
    - name: registry.blitzhub.io/docker:dind
      alias: docker
  before_script:
    - mkdir -p $TAR_FILE_DIR
    - *docker_login
  script:
    - docker pull aquasec/trivy:latest
    - docker tag aquasec/trivy:latest $TRIVY_IMAGE
    - docker save -o $TAR_FILE_DIR$TRIVY_TAR $TRIVY_IMAGE
    - echo "Trivy image created at $TAR_FILE_DIR$TRIVY_TAR"

  artifacts:
    paths:
      - $TAR_FILE_DIR
    expire_in: 1 hour


.security:licenses:
  stage: security
  dependencies:
    - security:prepare #overriden
  needs:
    - security:prepare #overriden
  image: docker:latest
  allow_failure: true
  services:
    - name: registry.blitzhub.io/docker:dind
      alias: docker
  before_script:
    - *docker_login
    - *load_target_image
    - *load_trivy_image
  script:
    # scan image for license issues to generate full report and filter for HIGH,CRITICAL report
    - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ -v $PWD:/target $TRIVY_IMAGE
      image --scanners license --exit-code 0 --cache-dir .trivycache/ --format json -o target/trivy-$REPORT_NAME-full-report.json $CI_IMAGE

    # format reports to html and junit and fail if HIGH,CRITICAL issues are found
    # currently license scanning does not suppor junit and html output -> they are always empty.
    - *format_report

  artifacts:
    <<: *export_reports

security:licenses:local:diabetes-staging:
  extends: .security:licenses
  dependencies:
    - check:build:local:diabetes-staging
    - security:prepare
  needs:
    - check:build:local:diabetes-staging
    - security:prepare
  variables:
    CI_IMAGE: CI_LOCAL_IMAGE_DIABETES
    REPORT_NAME: license-local-staging-diabetes
    TAR_FILE_NAME: $TAR_FILE_NAME_LOCAL_DIABETES
    TAG: staging


security:licenses:global:diabetes-staging:
  extends: .security:licenses
  dependencies:
    - check:build:global:diabetes-staging
    - security:prepare
  needs:
    - check:build:global:diabetes-staging
    - security:prepare
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_STAGING
    REPORT_NAME: license-global-staging
    TAR_FILE_NAME: $TAR_FILE_NAME_GLOBAL
    TAG: staging


security:filesystem:
  stage: security
  dependencies:
    - security:prepare
  needs:
    - security:prepare
  variables:
    REPORT_NAME: fs
  image: docker:latest
  allow_failure: true
  services:
    - name: registry.blitzhub.io/docker:dind
      alias: docker
  before_script:
    - *docker_login
    - *load_trivy_image
  script:
    # scan filesystem for misconfig,secret,vuln
    - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ -v $PWD:/target $TRIVY_IMAGE filesystem
      --scanners misconfig,secret,vuln --exit-code 0 --cache-dir .trivycache/ --format json -o target/trivy-$REPORT_NAME-full-report.json target

    # format reports to html and junit and fail if HIGH,CRITICAL issues are found
    - *format_report

  artifacts:
    <<: *export_reports

.security:images:
  stage: security
  dependencies:
    - security:prepare #overriden
  needs:
    - security:prepare #overriden
  image: docker:latest
  services:
    - name: registry.blitzhub.io/docker:dind
      alias: docker
  before_script:
    - *docker_login
    - *load_target_image
    - *load_trivy_image
  script:
    # scan image for license issues to generate full report and filter for HIGH,CRITICAL report
    - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ -v $PWD:/target $TRIVY_IMAGE
      image --exit-code 0 --cache-dir .trivycache/ --no-progress --format json -o target/trivy-$REPORT_NAME-full-report.json
      $CI_IMAGE
    # format reports to html and junit and fail if HIGH,CRITICAL issues are found
    - *format_report

  artifacts:
    <<: *export_reports

security:images:local:diabetes-staging:
  extends: .security:images
  dependencies:
    - check:build:local:diabetes-staging
    - security:prepare
  needs:
    - check:build:local:diabetes-staging
    - security:prepare
  allow_failure: true
  variables:
    CI_IMAGE: $CI_LOCAL_IMAGE_DIABETES_STAGING
    REPORT_NAME: image-local-staging-diabetes
    TAR_FILE_NAME: $TAR_FILE_NAME_LOCAL_DIABETES
    TAG: staging


security:images:global:diabetes-staging:
  extends: .security:images
  dependencies:
    - check:build:global:diabetes-staging
    - security:prepare
  needs:
    - check:build:global:diabetes-staging
    - security:prepare
  allow_failure: true
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_DIABETES_STAGING
    REPORT_NAME: image-global-staging-diabetes
    TAR_FILE_NAME: $TAR_FILE_NAME_GLOBAL-DIABETES
    TAG: staging


.deploy:gitlab_registry:
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - *docker_login
    - *docker_buildx
  script:
    - docker buildx build --platform linux/amd64,linux/arm64/v8 --provenance false -t $CI_IMAGE -f ./Dockerfile --push .

deploy:gitlab_registry:local:diabetes-staging:
  extends: .deploy:gitlab_registry
  needs:
    - assemble:local-daibetes
  only:
    - develop
  variables:
    CI_IMAGE: $CI_LOCAL_IMAGE_DIABETES_STAGING

deploy:gitlab_registry:local:diabetes-latest:
  extends: .deploy:gitlab_registry
  needs:
    - assemble:local-daibetes
  only:
    - main
  variables:
    CI_IMAGE: $CI_LOCAL_IMAGE_DIABETES_LATEST


deploy:gitlab_registry:local:microbaiome-staging:
  extends: .deploy:gitlab_registry
  needs:
    - assemble:local-microbaiome
  #only:
  #  - develop
  variables:
    CI_IMAGE: $CI_LOCAL_IMAGE_MICROBAIOME_STAGING


deploy:gitlab_registry:local:microbaiome-latest:
  extends: .deploy:gitlab_registry
  needs:
    - assemble:local-microbaiome
  only:
    - main
  variables:
    CI_IMAGE: $CI_LOCAL_IMAGE_MICROBAIOME_LATEST

  #GLOBAL

deploy:gitlab_registry:global:diabetes-staging:
  extends: .deploy:gitlab_registry
  needs:
    - assemble:global-daibetes
  #only:
  #  - develop
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_DIABETES_STAGING

deploy:gitlab_registry:global:diabetes-latest:
  extends: .deploy:gitlab_registry
  needs:
    - assemble:global-daibetes
  only:
    - main
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_DIABETES_LATEST


deploy:gitlab_registry:global:microbaiome-staging:
  extends: .deploy:gitlab_registry
  needs:
    - assemble:global-microbaiome
  #only:
  #  - develop
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_MICROBAIOME_STAGING

deploy:gitlab_registry:global:microbaiome-latest:
  extends: .deploy:gitlab_registry
  needs:
    - assemble:global-microbaiome
  only:
    - main
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_MICROBAIOME_LATEST


deploy:gitlab_registry:global:posymed-staging:
  extends: .deploy:gitlab_registry
  needs:
    - assemble:posymed
  #only:
  #  - develop
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_POSYMED_STAGING

deploy:gitlab_registry:global:posymed-latest:
  extends: .deploy:gitlab_registry
  needs:
    - assemble:posymed
  only:
    - main
  variables:
    CI_IMAGE: $CI_GLOBAL_IMAGE_POSYMED_LATEST
