FROM node:20-alpine AS builder
WORKDIR /app

COPY *.json ./
RUN npm i  --no-audit

COPY projects ./projects

RUN npm run build-local-dAIbetes


FROM nginx:stable-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/local-app-dAIbetes/browser /usr/share/nginx/html


EXPOSE 80
