export enum PublishStatus {
    PUBLISHED = 'PUBLISHED',
    UNPUBLISHED = 'UNPUBLISHED',

}

export enum FederatedAppType {
  PRE_PROCESSING = 'PRE_PROCESSING',
  ANALYSIS = 'ANALYSIS',
  SELF_LEARNED = 'SELF_LEARNED',
  DATA_TRANSFORMATION = 'DATA_TRANSFORMATION',
  EXTRACTOR = 'EXTRACTOR',
  POST_PROCESSING = 'POST_PROCESSING',
  EVALUATION = 'EVALUATION',
  EXPORT = 'EXPORT',
}
