export enum FlowActionPanelAction {
  CONNECT_SELECTED = 'CONNECT_SELECTED',
  DELETE_SELECTED = 'DELETE_SELECTED',
  ZOOM_IN = 'ZOOM_IN',
  ZOOM_OUT = 'ZOOM_OUT',
  FIT_TO_SCREEN = 'FIT_TO_SCREEN',
  ONE_TO_ONE= 'ONE_TO_ONE',
  RESET = 'RESET',
  SAVE = 'SAVE',
}
