export enum TestEmbedEnum {
  CLIENT_STARTED = "CLIENT_STARTED",
  CONFIG_CHANGED = "CONFIG_CHANGED",
  CLIENT_STOPPED = "CLIENT_STOPPED",
  CONFIG_CLIENT_SEND = "CONFIG_CLIENT_SEND",
  DATA_LIST_CLIENT_SEND = "DATA_LIST_CLIENT_SEND",
  CLIENT_ERROR = "CLIENT_ERROR",
  CLIENT_INFO = "CLIENT_INFO",
  APP_MESSAGE = "APP_MESSAGE",

  START_RUN = "START_RUN",
  UPDATE_RUN = "UPDATE_RUN",
  FINISH_RUN = "FINISH_RUN",

  START_FEDERATED_RUN = "START_FEDERATED_RUN",
  UPDATE_FEDERATED_RUN = "UPDATE_FEDERATED_RUN",
  FINISH_FEDERATED_RUN = "FINISH_FEDERATED_RUN",
  FEDERATED_PARTICIPANT_UPDATE = "FEDERATED_PARTICIPANT_UPDATE",
  FEDERATED_ROUND_MESSAGE = "FEDERATED_ROUND_MESSAGE",

  NOTIFY_START_EXPERIMENT = "NOTIFY_START_EXPERIMENT",

  SYSTEM_MESSAGE = "SYSTEM_MESSAGE",
  LOG_MESSAGE = "LOG_MESSAGE",
  APP_PERFORMANCE = "APP_PERFORMANCE",
  CONFIG_PYDANTIC_CHANGED = "CONFIG_PYDANTIC_CHANGED",
  CONSOLE_MESSAGE = "CONSOLE_MESSAGE",
  SERVER_ERROR = "SERVER_ERROR",
}

export enum RunType {
  TEST_RUN = "TEST_RUN",
  EXPERIMENT_RUN = "EXPERIMENT_RUN",
  PROJECT_RUN = "PROJECT_RUN",
  FEDERATED_RUN = "FEDERATED_RUN",
  NOT_DEFINED = "NOT_DEFINED"
}

export interface TestEmbedSocketWrapperDTO<T = object> {
  type: TestEmbedEnum
  runType: RunType
  message: T
}
